[문제-1] 길이가 10인 0-벡터를 만드세요.

In [25]:
import numpy as np
a = np.zeros(10, dtype = 'int32')
print(a)

[0 0 0 0 0 0 0 0 0 0]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [55]:
# b = np.eye(1, 10, 4, dtype = 'int32').reshape(-1)
# print(b)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [28]:
c = np.arange(10, 50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[문제-4] 위 벡터의 순서를 바꾸세요.

In [29]:
d= c[::-1]
print(d)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [30]:
print(np.arange(0, 9).reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [83]:
x = np.array([1,2,0,0,4,0])
y = x != 0
print(x[y])

[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [34]:
print(np.identity(3, dtype = 'int32'))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [80]:
import random

np.random.seed(0)
e = np.random.rand(3, 3)
print(e)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [81]:
print(f'최대값: {e.max()}')
print(f'최소값: {e.min()}')

최대값: 0.9636627605010293
최소값: 0.4236547993389047


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [82]:
print(f'열 평균: {np.mean(e, 1)}')
print(f'행 평균: {np.mean(e, 0)}')

열 평균: [0.62225542 0.53814403 0.76434099]
행 평균: [0.51042797 0.67687239 0.73744008]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [40]:
print(np.identity(5, dtype = 'int32'))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [85]:
v = np.random.randint(10, 51, 9)
print(v)

[18 19 30 26 15 25 10 28 45]


[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [87]:
print(v.reshape((3,3)))

[[18 19 30]
 [26 15 25]
 [10 28 45]]


 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [89]:
print(np.sum(v.reshape((3,3)), axis = 1))

[67 66 83]


[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [91]:
print(np.max(v.reshape((3,3)), axis = 0))

[26 28 45]


[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [95]:
print(np.mean(v.reshape((3,3)), dtype = 'int32'))

24


 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [107]:
z = np.random.randint(1,11, size = (2,3))
print(z)

[[2 4 4]
 [4 8 1]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [108]:
t = np.random.randint(1,20, size=(3,2))
print(t)

[[ 2 10]
 [ 1 11]
 [ 4 12]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [109]:
print(np.dot(z,t))

[[ 24 112]
 [ 20 140]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [110]:
print(np.dot(z,t).T)

[[ 24  20]
 [112 140]]


[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [111]:
np.random.seed(0)
lotto_nums = np.random.randint(1,47)
lotto = np.random.choice(lotto_nums, size = (6,), replace = False)
print(lotto)

[25 22 28  4 10 31]
